/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTheme"];
        put: operations["updateTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById"];
        post?: never;
        delete: operations["deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_1"];
        post: operations["addTaskByColumnId"];
        delete: operations["deleteById_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_2"];
        post?: never;
        delete: operations["deleteById_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}/subtasks/{subtaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_3"];
        post?: never;
        delete: operations["deleteById_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByUserId"];
        put?: never;
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByBoardId"];
        put?: never;
        post: operations["addColumnByBoardId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByTaskId"];
        put?: never;
        post: operations["addSubtaskByTaskId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["moveToColumn"];
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reorder"];
        trace?: never;
    };
    "/boards/{boardId}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findFullById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByColumnId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByBoardId_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateThemeRequestDTO: {
            /** @enum {string} */
            theme: "LIGHT" | "DARK";
        };
        UserResponseDTO: {
            id?: string;
            email?: string;
            displayName?: string;
            /** @enum {string} */
            theme?: "LIGHT" | "DARK";
        };
        UpdateBoardRequestDTO: {
            name?: string;
            /** Format: int64 */
            version: number;
        };
        BoardResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
        };
        UpdateColumnRequestDTO: {
            name: string;
            /** Format: int64 */
            version: number;
        };
        ColumnResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
        };
        UpdateTaskRequestDTO: {
            title?: string;
            description?: string;
            /** Format: int64 */
            version: number;
        };
        TaskResponseDTO: {
            id?: string;
            title?: string;
            description?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
        };
        UpdateSubtaskRequestDTO: {
            title?: string;
            isCompleted?: boolean;
            /** Format: int64 */
            version: number;
        };
        SubtaskResponseDTO: {
            id?: string;
            title?: string;
            isCompleted?: boolean;
            /** Format: int64 */
            version?: number;
        };
        SignupRequestDTO: {
            displayName?: string;
            email?: string;
            password?: string;
        };
        SigninRequestDTO: {
            email?: string;
            password?: string;
        };
        SaveBoardRequestDTO: {
            name: string;
        };
        SaveColumnRequestDTO: {
            name: string;
        };
        SaveTaskRequestDTO: {
            title: string;
            description?: string;
        };
        SaveSubtaskRequestDTO: {
            title?: string;
        };
        MoveTaskRequestDTO: {
            targetColumnId: string;
            /** Format: int64 */
            version: number;
            /** Format: int32 */
            targetPosition?: number;
        };
        ReorderColumnRequestDTO: {
            /** Format: int64 */
            version: number;
            /** Format: int32 */
            targetPosition: number;
        };
        BoardFullResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            columns?: components["schemas"]["ColumnFullResponseDTO"][];
        };
        ColumnFullResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
            tasks?: components["schemas"]["TaskFullResponseDTO"][];
        };
        TaskFullResponseDTO: {
            id?: string;
            title?: string;
            description?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
            subtasks?: components["schemas"]["SubtaskResponseDTO"][];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ActivityLogResponseDTO: {
            eventId?: string;
            /** @enum {string} */
            action?: "TASK_CREATED" | "TASK_MOVED" | "TASK_DELETED" | "TASK_UPDATED" | "BOARD_CREATED" | "BOARD_UPDATED" | "BOARD_DELETED" | "COLUMN_CREATED" | "COLUMN_DELETED" | "COLUMN_UPDATED" | "COLUMN_REORDERED" | "SUBTASK_CREATED" | "SUBTASK_UPDATED" | "SUBTASK_DELETED";
            detail?: string;
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageActivityLogResponseDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ActivityLogResponseDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTheme: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    updateTheme: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateThemeRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    updateById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"];
                };
            };
        };
    };
    deleteById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateById_1: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
        };
    };
    addTaskByColumnId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
        };
    };
    deleteById_1: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateById_2: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
        };
    };
    deleteById_2: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateById_3: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                subtaskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubtaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"];
                };
            };
        };
    };
    deleteById_3: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                subtaskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SigninRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    findAllByUserId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"][];
                };
            };
        };
    };
    save: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveBoardRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"];
                };
            };
        };
    };
    findAllByBoardId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"][];
                };
            };
        };
    };
    addColumnByBoardId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
        };
    };
    findAllByTaskId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"][];
                };
            };
        };
    };
    addSubtaskByTaskId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSubtaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"];
                };
            };
        };
    };
    moveToColumn: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
        };
    };
    reorder: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
        };
    };
    findFullById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardFullResponseDTO"];
                };
            };
        };
    };
    findAllByColumnId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
        };
    };
    findAllByBoardId_1: {
        parameters: {
            query: {
                userId: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageActivityLogResponseDTO"];
                };
            };
        };
    };
}
