/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTheme"];
        put: operations["updateTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById"];
        post?: never;
        delete: operations["deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_1"];
        post: operations["addTaskByColumnId"];
        delete: operations["deleteById_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_2"];
        post?: never;
        delete: operations["deleteById_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}/subtasks/{subtaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateById_3"];
        post?: never;
        delete: operations["deleteById_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByUserId"];
        put?: never;
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByBoardId"];
        put?: never;
        post: operations["addColumnByBoardId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks/{taskId}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByTaskId"];
        put?: never;
        post: operations["addSubtaskByTaskId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["moveToColumn"];
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reorder"];
        trace?: never;
    };
    "/boards/{boardId}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findFullById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/columns/{columnId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByColumnId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllByBoardId_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateThemeRequestDTO: {
            /** @enum {string} */
            theme: "LIGHT" | "DARK";
        };
        UserResponseDTO: {
            id?: string;
            email?: string;
            displayName?: string;
            /** @enum {string} */
            theme?: "LIGHT" | "DARK";
        };
        UpdateBoardRequestDTO: {
            name?: string;
            /** Format: int64 */
            version: number;
        };
        BoardResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateColumnRequestDTO: {
            name: string;
            /** Format: int64 */
            version: number;
        };
        ColumnResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
            color?: string;
        };
        UpdateTaskRequestDTO: {
            title?: string;
            description?: string;
            /** Format: int64 */
            version: number;
        };
        TaskResponseDTO: {
            id?: string;
            title?: string;
            description?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
        };
        UpdateSubtaskRequestDTO: {
            title?: string;
            isCompleted?: boolean;
            /** Format: int64 */
            version: number;
        };
        SubtaskResponseDTO: {
            id?: string;
            title?: string;
            isCompleted?: boolean;
            /** Format: int64 */
            version?: number;
        };
        SignupRequestDTO: {
            displayName?: string;
            email?: string;
            password?: string;
        };
        SigninRequestDTO: {
            email?: string;
            password?: string;
        };
        SaveBoardRequestDTO: {
            name: string;
        };
        SaveColumnRequestDTO: {
            name: string;
            color?: string;
        };
        SaveTaskRequestDTO: {
            title: string;
            description?: string;
        };
        SaveSubtaskRequestDTO: {
            title: string;
        };
        ResetUsersRequestDTO: {
            userIds: string[];
        };
        MoveTaskRequestDTO: {
            targetColumnId: string;
            /** Format: int64 */
            version: number;
            /** Format: int32 */
            targetPosition?: number;
        };
        ReorderColumnRequestDTO: {
            /** Format: int64 */
            version: number;
            /** Format: int32 */
            targetPosition: number;
        };
        BoardFullResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            columns?: components["schemas"]["ColumnFullResponseDTO"][];
        };
        ColumnFullResponseDTO: {
            id?: string;
            name?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
            color?: string;
            tasks?: components["schemas"]["TaskFullResponseDTO"][];
        };
        TaskFullResponseDTO: {
            id?: string;
            title?: string;
            description?: string;
            /** Format: int64 */
            version?: number;
            /** Format: int32 */
            position?: number;
            subtasks?: components["schemas"]["SubtaskResponseDTO"][];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ActivityLogResponseDTO: {
            eventId?: string;
            /** @enum {string} */
            action?: "TASK_CREATED" | "TASK_MOVED" | "TASK_DELETED" | "TASK_UPDATED" | "BOARD_CREATED" | "BOARD_UPDATED" | "BOARD_DELETED" | "COLUMN_CREATED" | "COLUMN_DELETED" | "COLUMN_UPDATED" | "COLUMN_REORDERED" | "SUBTASK_CREATED" | "SUBTASK_UPDATED" | "SUBTASK_DELETED";
            detail?: string;
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageActivityLogResponseDTO: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ActivityLogResponseDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        /** @description The RFC 7807 envelope every error response in this API uses. */
        ProblemDetail: {
            /**
             * Format: uri
             * @description Always 'about:blank' unless a more specific type is set.
             */
            type?: string;
            /** @description Absent unless explicitly set -- both producers build the envelope through ProblemDetail.forStatusAndDetail, which populates status and detail only. */
            title?: string;
            /** Format: int32 */
            status: number;
            detail?: string;
            /**
             * Format: uri
             * @description The authentication entry point sets this explicitly so both producers' key sets agree.
             */
            instance?: string;
            /** @enum {string} */
            code: "ENTITY_NOT_FOUND" | "ILLEGAL_ARGUMENT" | "MALFORMED_REQUEST_BODY" | "INTERNAL_ERROR" | "ACCESS_DENIED" | "CONSTRAINT_VIOLATION" | "OPTIMISTIC_LOCK_CONFLICT" | "DUPLICATE_RESOURCE" | "DATA_INTEGRITY_VIOLATION" | "BAD_CREDENTIALS" | "VALIDATION_FAILED" | "UNAUTHENTICATED";
            /** @description Present only on the field-validation response: field name to message. */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTheme: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateTheme: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateThemeRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateById_1: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    addTaskByColumnId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteById_1: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateById_2: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteById_2: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    updateById_3: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                subtaskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubtaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    deleteById_3: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                subtaskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SigninRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findAllByUserId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"][];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    save: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveBoardRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findAllByBoardId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"][];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    addColumnByBoardId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findAllByTaskId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"][];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    addSubtaskByTaskId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSubtaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubtaskResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: {
                "X-Reset-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetUsersRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    moveToColumn: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    reorder: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderColumnRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findFullById: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardFullResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findAllByColumnId: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path: {
                columnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TaskResponseDTO"][];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    findAllByBoardId_1: {
        parameters: {
            query: {
                userId: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageActivityLogResponseDTO"];
                };
            };
            /** @description Malformed request body, failed field validation (VALIDATION_FAILED, with a per-field errors map), or a violated path/param constraint (CONSTRAINT_VIOLATION / ILLEGAL_ARGUMENT / MALFORMED_REQUEST_BODY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No session at all (UNAUTHENTICATED, produced by ProblemDetailAuthenticationEntryPoint) or rejected credentials on signin (BAD_CREDENTIALS, produced by GlobalExceptionHandler). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An authenticated caller who does not own the requested resource (ACCESS_DENIED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The requested resource does not exist or is not visible to the caller (ENTITY_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic-lock version mismatch (OPTIMISTIC_LOCK_CONFLICT), a duplicate resource (DUPLICATE_RESOURCE), or a database integrity violation (DATA_INTEGRITY_VIOLATION). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description An unhandled server-side failure (INTERNAL_ERROR). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
