#!/usr/bin/env node
/*
 * GC-04: fails the build if a hardcoded application-path literal reappears outside
 * `src/lib/core/routing/routes.ts`, the one place any application path is declared (`ROUTE`).
 * Scans the `app/`, `src/` and `e2e/` directories plus the guard file at the repository root for
 * a quoted string matching the sign-in, sign-up or board-list path — the three multi-character
 * paths where drift actually happens. The landing path ("/") is deliberately not checked: a bare
 * single-character path is too common a substring (empty-string defaults, root-relative asset
 * URLs, etc.) to gate on without constant false positives.
 *
 * `src/lib/core/api-contract/generated-types.ts` is excluded — it is `openapi-typescript` output
 * describing the *backend* REST contract's own path keys (e.g. the external API's `/boards`
 * resource), regenerated by `pnpm api:generate` and unrelated to this app's frontend page routes.
 */
import { globSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

const ROUTE_PATH_PATTERN = /"\/(login|register|boards)"/g;

const EXCLUDED_FILES = new Set(
    ["src/lib/core/routing/routes.ts", "src/lib/core/api-contract/generated-types.ts"].map((p) =>
        path.resolve(repoRoot, p),
    ),
);

const SEARCH_GLOBS = ["app/**/*.{ts,tsx}", "src/**/*.{ts,tsx}", "e2e/**/*.{ts,tsx}"];

const files = new Set(SEARCH_GLOBS.flatMap((pattern) => globSync(pattern, { cwd: repoRoot })));
files.add("proxy.ts");

const violations = [];

for (const relativePath of files) {
    const absolutePath = path.resolve(repoRoot, relativePath);
    if (EXCLUDED_FILES.has(absolutePath)) {
        continue;
    }

    const contents = readFileSync(absolutePath, "utf8");
    const lines = contents.split("\n");

    lines.forEach((line, index) => {
        ROUTE_PATH_PATTERN.lastIndex = 0;
        if (ROUTE_PATH_PATTERN.test(line)) {
            violations.push(`${relativePath}:${String(index + 1)}: ${line.trim()}`);
        }
    });
}

if (violations.length > 0) {
    console.error(
        "routes:check failed — hardcoded application-path literal(s) found outside src/lib/core/routing/routes.ts:\n",
    );
    for (const violation of violations) {
        console.error(`  ${violation}`);
    }
    console.error("\nImport ROUTE from '@/lib/core/routing/routes' (or the relative equivalent) instead.");
    process.exit(1);
}

console.log("routes:check passed — no application-path literal found outside src/lib/core/routing/routes.ts.");
